
import DetectAI from "@/components/section/detectAI";
import HeroBanner from "@/components/section/heroBanner";
import Plans from "@/components/section/plans";
import Powerful from "@/components/section/powerful";
import Queries from "@/components/section/queries";
import Review from "@/components/section/review";
import Update from "@/components/section/update";
import WhoUse from "@/components/section/whoUse";
import WhyChoose from "@/components/section/whyChoose";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>AI Detector</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroBanner />
      <DetectAI />
      <Powerful />
      <WhyChoose />
      <WhoUse />
      <Review />
      <Plans />
      <Queries />
      <Update />
    </>
  );
}
